// shared head
const HEAD = [
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">',
    '<meta name="robots" content="noindex, nofollow">',

    '<link rel="stylesheet" href="/style.css">',
    '<link rel="stylesheet" href="/themes.css">',
    '<script>try{var t=localStorage.getItem("zoneoutTheme");if(t&&t!=="default"&&/^[a-z0-9-]{1,24}$/.test(t))document.documentElement.setAttribute("data-theme",t);}catch(e){}<\/script>',
    '<link rel="icon" href="/favicon.svg" type="image/svg+xml">',
    '<link rel="icon" href="/favicon.ico" sizes="32x32">',
    '<link rel="apple-touch-icon" href="/apple-touch-icon.png">'
].join("\n");

// what everyone who is not an administrator receives
export const NOT_FOUND_PAGE = [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    HEAD,
    "<title>Not Found</title>",
    "<style>",
    "body{background:rgb(var(--bg));color:rgb(var(--fg));line-height:1.6;min-height:100vh;min-height:100dvh;display:flex;",
    "flex-direction:column;align-items:center;justify-content:center;gap:26px;padding:24px;text-align:center;}",
    ".errCode{font-size:clamp(28px,7vw,44px);letter-spacing:4px;}",
    ".errText{opacity:0.7;letter-spacing:2px;}",
    "</style>",
    "</head>",
    "<body>",
    '<div class="errCode">404: PAGE NOT FOUND</div>',
    '<div class="errText">There is nothing at this address.</div>',
    '<button class="camNode" id="toMenuBtn" type="button">&larr; RETURN TO MAIN MENU</button>',
    "<script>",
    "document.getElementById('toMenuBtn').addEventListener('click', function () {",
    "  window.location.href = '/';",
    "});",
    "</script>",
    "</body>",
    "</html>"
].join("\n");

// the dashboard
export const ADMIN_PAGE = [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    HEAD,
    "<title>ZoneOut Admin</title>",
    "<style>",
    adminCss(),
    "</style>",
    "</head>",
    "<body>",
    adminBody(),
    "<script>",
    adminScript(),
    "</script>",
    "</body>",
    "</html>"
].join("\n");

// styling
function adminCss() {
    return [
        "body{background:rgb(var(--bg));color:rgb(var(--fg));line-height:1.6;min-height:100vh;padding:28px 20px 140px;}",

        ".adminTop{display:flex;flex-wrap:wrap;gap:18px;align-items:flex-start;",
        "justify-content:space-between;width:min(1180px,100%);margin:0 auto 26px;}",
        ".adminTitle{font-size:clamp(24px,4vw,34px);letter-spacing:6px;font-weight:bold;}",
        ".adminSub{margin-top:6px;font-size:14px;opacity:0.55;letter-spacing:2px;}",

        ".searchBox{margin-top:14px;width:min(420px,100%);}",
        ".searchBox label{display:block;font-size:13px;letter-spacing:3px;opacity:0.55;margin-bottom:6px;}",
        ".searchBox input{width:100%;}",
        ".searchHint{margin-top:6px;font-size:12px;opacity:0.42;line-height:1.6;}",

        ".queryBox{width:min(420px,100%);}",
        ".queryBox label{display:block;font-size:13px;letter-spacing:3px;opacity:0.55;margin-bottom:6px;}",
        ".queryBox input{width:100%;}",
        ".queryHint{margin-top:6px;font-size:12px;opacity:0.42;line-height:1.6;}",

        "input[type=text]{background:rgba(var(--panelBot),0.9);color:rgb(var(--fg));border:1px solid rgba(var(--accent),0.35);",
        "padding:9px 11px;font-size:15px;font-family:'Courier New',monospace;border-radius:4px;}",
        "input[type=text]:focus{outline:none;border-color:rgba(var(--accentBright),0.9);",
        "box-shadow:0 0 12px rgba(var(--accentGlow),0.35);}",

        ".adminTabs{display:flex;gap:10px;margin-bottom:10px;justify-content:flex-end;}",
        ".adminTabs .camNode{padding:7px 12px;font-size:13px;letter-spacing:2px;}",
        ".adminTabs .camNode.on{border-color:rgba(var(--accentBright),0.9);",
        "box-shadow:0 0 12px rgba(var(--accentGlow),0.35);}",

        ".tableWrap[hidden]{display:none;}",
        ".tableWrap{width:min(1180px,100%);margin:0 auto;overflow:auto;overscroll-behavior:contain;",
        "max-height:calc(100dvh - 300px);min-height:180px;",
        "scrollbar-color:rgba(var(--accentBright),0.85) rgba(var(--panelBot),0.9);",
        "border:1px solid rgba(var(--accent),0.35);box-shadow:0 0 18px rgba(var(--accentGlow),0.18);",
        "background:linear-gradient(135deg, rgba(var(--panelTop),0.96), rgba(var(--panelBot),0.96));}",
        "body.hasPending .tableWrap{max-height:calc(100dvh - 460px);}",
        ".tableWrap::-webkit-scrollbar{width:14px;height:14px;}",
        ".tableWrap::-webkit-scrollbar-track{background:rgba(var(--panelBot),0.9);}",
        ".tableWrap::-webkit-scrollbar-thumb{background:rgba(var(--accent),0.75);",
        "border:3px solid rgba(var(--panelBot),0.9);border-radius:8px;}",
        ".tableWrap::-webkit-scrollbar-thumb:hover{background:rgba(var(--accentBright),0.95);}",
        ".tableWrap::-webkit-scrollbar-corner{background:rgba(var(--panelBot),0.9);}",
        "table{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0;font-size:14px;}",
        "th,td{padding:10px 12px;text-align:left;border-bottom:1px dashed rgba(var(--fg),0.12);",
        "white-space:nowrap;}",
        "th{font-size:12px;letter-spacing:2px;color:rgba(var(--fg),0.45);font-weight:normal;",
        "position:sticky;top:0;z-index:2;background:rgb(var(--panelTop));",
        "box-shadow:inset 0 -1px 0 rgba(var(--accent),0.45);}",
        "tr:last-child td{border-bottom:none;}",
        "td.wrap{white-space:normal;word-break:break-all;max-width:280px;}",
        "td.reason{white-space:normal;max-width:520px;line-height:1.6;}",
        ".balanceInput{width:96px;}",
        ".banned{color:rgb(var(--danger));letter-spacing:2px;}",
        ".projectIds{opacity:0.75;}",
        ".empty{padding:24px;text-align:center;opacity:0.6;}",
        "tr[hidden]{display:none;}",
        "td a{color:rgb(var(--accentLink));}",
        "mark{background:rgba(var(--accentBright),0.35);color:rgb(var(--fg));}",

        ".pending{position:fixed;left:50%;bottom:0;transform:translateX(-50%);",
        "width:min(1180px,100%);z-index:230;padding:14px 18px;",
        "background:linear-gradient(135deg, rgba(var(--panelTop),0.98), rgba(var(--panelBot),0.98));",
        "border:1px solid rgba(var(--accent),0.35);border-bottom:none;",
        "box-shadow:0 -8px 30px rgba(var(--bg),0.7);display:none;}",
        ".pending.show{display:flex;gap:16px;align-items:center;flex-wrap:wrap;}",
        ".pendingList{flex:1;min-width:220px;max-height:120px;overflow-y:auto;font-size:13px;line-height:1.8;}",
        ".pendingList div{opacity:0.85;}",

        ".adminMsg{width:min(1180px,100%);margin:16px auto 0;font-size:14px;line-height:1.7;min-height:20px;}",
        ".adminMsg.bad{color:rgb(var(--danger));}",

        "@media (max-width:700px){",
        ".tableWrap{max-height:calc(100dvh - 220px);}",
        ".adminTop{flex-direction:column;}",
        ".queryBox{width:100%;}",
        ".searchBox{width:100%;}",
        "}"
    ].join("\n");
}

// markup
function adminBody() {
    return [
        '<div class="adminTop">',
        "<div>",
        '<div class="adminTitle">ADMIN</div>',
        '<div class="adminSub" id="adminCount">loading&hellip;</div>',

        '<div class="searchBox">',
        '<label for="searchInput">SEARCH RECORDS</label>',
        '<input id="searchInput" type="text" autocomplete="off" spellcheck="false" placeholder="name, email, id, keyword">',
        '<div class="searchHint">Filters as you type. Every word must match. Escape clears.</div>',
        "</div>",
        "</div>",

        '<div class="queryBox">',
        '<div class="adminTabs">',
        '<button class="camNode on" id="tabUsers" type="button">USERS</button>',
        '<button class="camNode" id="tabProjects" type="button">PROJECTS</button>',
        '<button class="camNode" id="tabSuggestions" type="button">SHOP SUGGESTIONS</button>',
        "</div>",
        '<label for="queryInput">QUERIES</label>',
        '<input id="queryInput" type="text" autocomplete="off" spellcheck="false" placeholder="DELETE 4 17">',
        '<div class="queryHint">',
        "DELETE &lt;user_id&gt; &lt;project_id&gt; &nbsp;&middot;&nbsp; ",
        "BAN &lt;user_id&gt; &lt;reason&gt; &nbsp;&middot;&nbsp; ",
        "UNBAN &lt;user_id&gt; &nbsp;&middot;&nbsp; ",
        "&lt;user_id&gt; ACCESS CG true|false<br>Press Enter to stage, then Save.",
        "</div>",
        "</div>",
        "</div>",

        '<div class="tableWrap" id="userWrap">',
        "<table>",
        "<thead><tr>",
        "<th>USER_ID</th><th>USERNAME</th><th>EMAIL</th><th>SLACK_ID</th><th>REGION</th>",
        "<th>HOUR_BALANCE</th><th>PROJECT_IDS</th><th>STATE</th>",
        "</tr></thead>",
        '<tbody id="adminRows"></tbody>',
        "</table>",
        '<div class="empty" id="adminEmpty">Loading&hellip;</div>',
        "</div>",

        '<div class="tableWrap" id="projectWrap" hidden>',
        "<table>",
        "<thead><tr>",
        "<th>PROJECT_ID</th><th>USER_ID</th><th>SLACK_ID</th><th>USERNAME</th><th>PROJECT_NAME</th>",
        "<th>HACKATIME_PROJECT</th><th>ACTIVE_HOURS</th><th>REGION</th><th>PROJECT_PAGE</th>",
        "<th>LINKS</th><th>CREATED</th>",
        "</tr></thead>",
        '<tbody id="projectRows"></tbody>',
        "</table>",
        '<div class="empty" id="projectEmpty">Loading&hellip;</div>',
        "</div>",

        '<div class="tableWrap" id="suggestionWrap" hidden>',
        "<table>",
        "<thead><tr>",
        "<th>ID</th><th>USER_ID</th><th>USERNAME</th><th>REGION</th>",
        "<th>SUGGESTED_ITEM</th><th>REASON</th><th>WHEN</th>",
        "</tr></thead>",
        '<tbody id="suggestionRows"></tbody>',
        "</table>",
        '<div class="empty" id="suggestionEmpty">Loading&hellip;</div>',
        "</div>",

        '<div class="adminMsg" id="adminMsg" role="status" aria-live="polite"></div>',

        '<div class="pending" id="pending">',
        '<div class="pendingList" id="pendingList"></div>',
        '<button class="camNode" id="discardBtn" type="button">DISCARD</button>',
        '<button class="camNode" id="saveBtn" type="button">SAVE</button>',
        "</div>"
    ].join("\n");
}

// behaviour
function adminScript() {
    return [
        '"use strict";',

        "var rowsEl = document.getElementById('adminRows');",
        "var emptyEl = document.getElementById('adminEmpty');",
        "var countEl = document.getElementById('adminCount');",
        "var msgEl = document.getElementById('adminMsg');",
        "var pendingEl = document.getElementById('pending');",
        "var pendingListEl = document.getElementById('pendingList');",
        "var queryInput = document.getElementById('queryInput');",
        "var saveBtn = document.getElementById('saveBtn');",
        "var userWrap = document.getElementById('userWrap');",
        "var suggestionWrap = document.getElementById('suggestionWrap');",
        "var suggestionRowsEl = document.getElementById('suggestionRows');",
        "var suggestionEmptyEl = document.getElementById('suggestionEmpty');",
        "var tabUsers = document.getElementById('tabUsers');",
        "var searchInput = document.getElementById('searchInput');",
        "var tabSuggestions = document.getElementById('tabSuggestions');",
        "var tabProjects = document.getElementById('tabProjects');",
        "var projectWrap = document.getElementById('projectWrap');",
        "var projectRowsEl = document.getElementById('projectRows');",
        "var projectEmptyEl = document.getElementById('projectEmpty');",

        "// staged edits, nothing written until Save",
        "var stagedBalances = new Map();",
        "var stagedCommands = [];",
        "var users = [];",

        "// live search index, one entry per drawn row",
        "var userIndex = [];",
        "var suggestionIndex = [];",
        "var suggestionsDrawn = false;",
        "var projectIndex = [];",
        "var projectsDrawn = false;",

        "function say(text, bad) {",
        "  msgEl.textContent = text || '';",
        "  msgEl.classList.toggle('bad', Boolean(bad));",
        "}",

        "// a 404 means this session is no longer an administrator",
        "function handleGone(response) {",
        "  if (response.status === 404) { location.reload(); return true; }",
        "  return false;",
        "}",

        "function load() {",
        "  fetch('/api/admin/users', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the user list.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) render(data.users); })",
        "    .catch(function (err) {",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      emptyEl.textContent = 'Could not load.';",
        "    });",
        "}",

        "function render(list) {",
        "  users = list || [];",
        "  rowsEl.textContent = '';",
        "  userIndex = [];",

        "  users.forEach(function (user) {",
        "    var tr = document.createElement('tr');",
        "    tr.appendChild(cell(String(user.userId)));",
        "    tr.appendChild(cell(user.name || '\\u2014'));",
        "    tr.appendChild(cell(user.email, 'wrap'));",
        "    tr.appendChild(cell(user.slackId || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(user.region || '\\u2014'));",

        "    // balance field",
        "    var td = document.createElement('td');",
        "    var input = document.createElement('input');",
        "    input.type = 'text';",
        "    input.className = 'balanceInput';",
        "    input.value = String(user.balanceHours);",
        "    input.setAttribute('aria-label', 'Hour balance for user ' + user.userId);",
        "    input.addEventListener('input', function () {",
        "      var raw = input.value.trim();",
        "      var value = Number(raw);",
        "      if (raw === '' || !isFinite(value) || value < 0 || value === user.balanceHours) {",
        "        stagedBalances['delete'](user.userId);",
        "      } else {",
        "        stagedBalances.set(user.userId, value);",
        "      }",
        "      renderPending();",
        "    });",
        "    td.appendChild(input);",
        "    tr.appendChild(td);",

        "    var ids = Array.isArray(user.projectIds) ? user.projectIds : [];",
        "    tr.appendChild(cell(ids.length ? ids.join(', ') : '\\u2014', 'projectIds'));",

        "    var state = document.createElement('td');",
        "    if (user.isBanned) {",
        "      state.className = 'banned';",
        "      state.textContent = 'BANNED';",
        "      state.title = user.banReason || '';",
        "    } else {",
        "      state.textContent = user.status + (user.hackatimeLinked ? ' + hackatime' : '')",
        "                          + (user.cgAccess ? ' + cg' : '');",
        "    }",
        "    state.dataset.text = state.textContent;",
        "    tr.appendChild(state);",
        "    rowsEl.appendChild(tr);",
        "    indexRow(userIndex, tr, String(user.balanceHours) + ' ' + (user.banReason || ''));",
        "  });",

        "  applyFilter();",
        "  renderPending();",
        "}",

        "// table cells",
        "function cell(text, className) {",
        "  var td = document.createElement('td');",
        "  if (className) td.className = className;",
        "  td.textContent = text;",
        "  td.dataset.text = text;",
        "  return td;",
        "}",

        "function renderPending() {",
        "  var lines = [];",
        "  stagedBalances.forEach(function (hours, userId) {",
        "    lines.push('set user ' + userId + ' balance to ' + hours);",
        "  });",
        "  stagedCommands.forEach(function (raw) { lines.push(raw); });",

        "  pendingListEl.textContent = '';",
        "  lines.forEach(function (line) {",
        "    var div = document.createElement('div');",
        "    div.textContent = '\\u203a ' + line;",
        "    pendingListEl.appendChild(div);",
        "  });",

        "  pendingEl.classList.toggle('show', lines.length > 0);",
        "  document.body.classList.toggle('hasPending', lines.length > 0);",
        "}",

        "// command box",
        "queryInput.addEventListener('keydown', function (e) {",
        "  if (e.key !== 'Enter') return;",
        "  e.preventDefault();",
        "  var raw = queryInput.value.trim();",
        "  if (!raw) return;",
        "  stagedCommands.push(raw);",
        "  queryInput.value = '';",
        "  say('');",
        "  renderPending();",
        "});",

        "document.getElementById('discardBtn').addEventListener('click', function () {",
        "  stagedBalances.clear();",
        "  stagedCommands = [];",
        "  say('Discarded.');",
        "  render(users);",
        "});",

        "saveBtn.addEventListener('click', function () {",
        "  var balances = [];",
        "  stagedBalances.forEach(function (hours, userId) {",
        "    balances.push({ userId: userId, balanceHours: hours });",
        "  });",
        "  if (!balances.length && !stagedCommands.length) return;",

        "  saveBtn.disabled = true;",
        "  say('Saving\\u2026');",

        "  fetch('/api/admin/apply', {",
        "    method: 'POST',",
        "    credentials: 'same-origin',",
        "    headers: { 'Content-Type': 'application/json' },",
        "    body: JSON.stringify({ balances: balances, commands: stagedCommands })",
        "  })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      return r.json().then(function (data) { return { ok: r.ok, data: data }; });",
        "    })",
        "    .then(function (result) {",
        "      if (!result) return;",
        "      if (!result.ok) {",
        "        // the batch rolled back; staged changes stay put",
        "        say(result.data.error || 'Could not save.', true);",
        "        return;",
        "      }",
        "      stagedBalances.clear();",
        "      stagedCommands = [];",
        "      if (result.data.users) { render(result.data.users); } else { load(); }",
        "      say('Saved: ' + (result.data.applied || []).join('; '));",
        "    })",
        "    .catch(function () { say('Could not reach ZoneOut.', true); })",
        "    .then(function () { saveBtn.disabled = false; });",
        "});",

        "// live search",
        "function indexRow(index, tr, extra) {",
        "  var cells = [];",
        "  var tds = tr.querySelectorAll('td');",
        "  for (var i = 0; i < tds.length; i++) {",
        "    if (typeof tds[i].dataset.text === 'string') cells.push({ td: tds[i], text: tds[i].dataset.text });",
        "  }",
        "  var text = cells.map(function (c) { return c.text; }).join(' ') + ' ' + (extra || '');",
        "  index.push({ tr: tr, cells: cells, text: text.toLowerCase() });",
        "}",

        "function searchTerms() {",
        "  var raw = searchInput.value.trim().toLowerCase();",
        "  return raw ? raw.split(/\\s+/) : [];",
        "}",

        "function termPattern(terms) {",
        "  if (!terms.length) return null;",
        "  var escaped = terms.map(function (t) { return t.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&'); });",
        "  return new RegExp('(' + escaped.join('|') + ')', 'gi');",
        "}",

        "function paintCell(td, text, pattern) {",
        "  if (!pattern) { td.textContent = text; return; }",
        "  td.textContent = '';",
        "  var last = 0;",
        "  var match;",
        "  pattern.lastIndex = 0;",
        "  while ((match = pattern.exec(text)) !== null) {",
        "    if (!match[0]) { pattern.lastIndex++; continue; }",
        "    if (match.index > last) td.appendChild(document.createTextNode(text.slice(last, match.index)));",
        "    var hit = document.createElement('mark');",
        "    hit.textContent = match[0];",
        "    td.appendChild(hit);",
        "    last = match.index + match[0].length;",
        "  }",
        "  if (last < text.length) td.appendChild(document.createTextNode(text.slice(last)));",
        "}",

        "function filterIndex(index, terms, pattern) {",
        "  var shown = 0;",
        "  index.forEach(function (row) {",
        "    var hit = terms.every(function (term) { return row.text.indexOf(term) !== -1; });",
        "    row.tr.hidden = !hit;",
        "    if (!hit) return;",
        "    shown++;",
        "    row.cells.forEach(function (c) { paintCell(c.td, c.text, pattern); });",
        "  });",
        "  return shown;",
        "}",

        "function applyFilter() {",
        "  var terms = searchTerms();",
        "  var pattern = termPattern(terms);",
        "  var shownUsers = filterIndex(userIndex, terms, pattern);",
        "  var shownSuggestions = filterIndex(suggestionIndex, terms, pattern);",
        "  var shownProjects = filterIndex(projectIndex, terms, pattern);",

        "  countEl.textContent = terms.length",
        "    ? shownUsers + ' of ' + userIndex.length + ' users matched'",
        "    : userIndex.length + ' registered';",

        "  emptyEl.style.display = shownUsers ? 'none' : '';",
        "  emptyEl.textContent = userIndex.length ? 'No records match.' : 'No one has registered yet.';",

        "  if (projectsDrawn) {",
        "    projectEmptyEl.style.display = shownProjects ? 'none' : '';",
        "    projectEmptyEl.textContent = projectIndex.length ? 'No records match.' : 'No projects have been created yet.';",
        "  }",

        "  if (suggestionsDrawn) {",
        "    suggestionEmptyEl.style.display = shownSuggestions ? 'none' : '';",
        "    suggestionEmptyEl.textContent = suggestionIndex.length ? 'No records match.' : 'Nobody has suggested anything yet.';",
        "  }",
        "}",

        "searchInput.addEventListener('input', applyFilter);",

        "searchInput.addEventListener('keydown', function (e) {",
        "  if (e.key !== 'Escape') return;",
        "  searchInput.value = '';",
        "  applyFilter();",
        "});",

        "// tabs",
        "var suggestionsLoaded = false;",

        "function showTab(name) {",
        "  userWrap.hidden = name !== 'users';",
        "  projectWrap.hidden = name !== 'projects';",
        "  suggestionWrap.hidden = name !== 'suggestions';",
        "  tabUsers.classList.toggle('on', name === 'users');",
        "  tabProjects.classList.toggle('on', name === 'projects');",
        "  tabSuggestions.classList.toggle('on', name === 'suggestions');",
        "  if (name === 'projects') loadProjects();",
        "  if (name === 'suggestions') loadSuggestions();",
        "}",

        "var projectsLoaded = false;",

        "function loadProjects() {",
        "  if (projectsLoaded) return;",
        "  projectsLoaded = true;",

        "  fetch('/api/admin/projects', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the project list.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) renderProjects(data.projects); })",
        "    .catch(function (err) {",
        "      projectsLoaded = false;",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      projectEmptyEl.textContent = 'Could not load.';",
        "    });",
        "}",

        "function renderProjects(list) {",
        "  var rows = list || [];",
        "  projectRowsEl.textContent = '';",
        "  projectIndex = [];",
        "  projectsDrawn = true;",

        "  rows.forEach(function (row) {",
        "    var tr = document.createElement('tr');",
        "    tr.appendChild(cell(String(row.projectId)));",
        "    tr.appendChild(cell(String(row.userId)));",
        "    tr.appendChild(cell(row.slackId || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(row.ownerName || '\u2014'));",
        "    tr.appendChild(cell(row.name || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(row.hackatimeProject || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(String(Number(row.hackatimeHours) || 0)));",
        "    tr.appendChild(cell(row.region || '\u2014'));",
        "    tr.appendChild(projectPage(row.projectId));",
        "    tr.appendChild(links(row));",
        "    tr.appendChild(cell(when(row.createdAt)));",
        "    projectRowsEl.appendChild(tr);",
        "    indexRow(projectIndex, tr, (row.email || '') + ' ' + (row.description || '')",
        "                                + ' /projects/' + row.projectId);",
        "  });",

        "  applyFilter();",
        "}",

        "// the project's own page on zoneout",
        "function projectPage(projectId) {",
        "  var td = document.createElement('td');",
        "  var path = '/projects/' + projectId;",
        "  var a = document.createElement('a');",
        "  a.href = path;",
        "  a.target = '_blank';",
        "  a.rel = 'noopener noreferrer';",
        "  a.textContent = path;",
        "  td.appendChild(a);",
        "  return td;",
        "}",

        "// only http and https are ever rendered as a link",
        "function safeUrl(value) {",
        "  if (typeof value !== 'string' || !value) return false;",
        "  try {",
        "    var protocol = new URL(value, location.href).protocol;",
        "    return protocol === 'http:' || protocol === 'https:';",
        "  } catch (err) { return false; }",
        "}",

        "// repository and demo links",
        "function links(row) {",
        "  var td = document.createElement('td');",
        "  var pairs = [['repo', row.repoUrl], ['demo', row.demoUrl]];",
        "  var drawn = 0;",
        "  pairs.forEach(function (pair) {",
        "    if (!safeUrl(pair[1])) return;",
        "    if (drawn) td.appendChild(document.createTextNode(' \u00b7 '));",
        "    var a = document.createElement('a');",
        "    a.href = pair[1];",
        "    a.target = '_blank';",
        "    a.rel = 'noopener noreferrer nofollow';",
        "    a.textContent = pair[0];",
        "    td.appendChild(a);",
        "    drawn++;",
        "  });",
        "  if (!drawn) { td.textContent = '\u2014'; td.dataset.text = '\u2014'; }",
        "  return td;",
        "}",

        "function loadSuggestions() {",
        "  if (suggestionsLoaded) return;",
        "  suggestionsLoaded = true;",

        "  fetch('/api/admin/suggestions', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the suggestions.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) renderSuggestions(data.suggestions); })",
        "    .catch(function (err) {",
        "      suggestionsLoaded = false;",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      suggestionEmptyEl.textContent = 'Could not load.';",
        "    });",
        "}",

        "function renderSuggestions(list) {",
        "  var rows = list || [];",
        "  suggestionRowsEl.textContent = '';",
        "  suggestionIndex = [];",
        "  suggestionsDrawn = true;",

        "  rows.forEach(function (row) {",
        "    var tr = document.createElement('tr');",
        "    tr.appendChild(cell(String(row.suggestionId)));",
        "    tr.appendChild(cell(String(row.userId)));",
        "    tr.appendChild(cell(row.userName || '\u2014'));",
        "    tr.appendChild(cell(row.region || '\u2014'));",
        "    tr.appendChild(cell(row.itemName, 'wrap'));",
        "    tr.appendChild(cell(row.reason, 'reason'));",
        "    tr.appendChild(cell(when(row.createdAt)));",
        "    suggestionRowsEl.appendChild(tr);",
        "    indexRow(suggestionIndex, tr, '');",
        "  });",

        "  applyFilter();",
        "}",

        "function when(value) {",
        "  var date = new Date(value);",
        "  return isNaN(date.getTime()) ? '\u2014' : date.toLocaleString();",
        "}",

        "tabUsers.addEventListener('click', function () { showTab('users'); });",
        "tabProjects.addEventListener('click', function () { showTab('projects'); });",
        "tabSuggestions.addEventListener('click', function () { showTab('suggestions'); });",

        "load();"
    ].join("\n");
}
