// shared head
const HEAD = [
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">',
    '<meta name="robots" content="noindex, nofollow">',

    '<link rel="stylesheet" href="/style.css">',
    '<link rel="stylesheet" href="/themes.css">',
    '<script>try{var t=localStorage.getItem("zoneoutTheme")||"fnaf";if(t!=="default"&&/^[a-z0-9-]{1,24}$/.test(t))document.documentElement.setAttribute("data-theme",t);}catch(e){}<\/script>',
    '<link rel="icon" href="/favicon.svg" type="image/svg+xml">',
    '<link rel="icon" href="/favicon.ico" sizes="32x32">',
    '<link rel="apple-touch-icon" href="/apple-touch-icon.png">'
].join("\n");

// what everyone who is not an administrator receives
export const NOT_FOUND_PAGE = [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    HEAD,
    "<title>Not Found</title>",
    "<style>",
    "body{background:rgb(var(--bg));color:rgb(var(--fg));line-height:1.6;min-height:100vh;min-height:100dvh;display:flex;",
    "flex-direction:column;align-items:center;justify-content:center;gap:26px;padding:24px;text-align:center;}",
    ".errCode{font-size:clamp(28px,7vw,44px);letter-spacing:4px;}",
    ".errText{opacity:0.7;letter-spacing:2px;}",
    "</style>",
    "</head>",
    "<body>",
    '<div class="errCode">404: PAGE NOT FOUND</div>',
    '<div class="errText">There is nothing at this address.</div>',
    '<button class="camNode" id="toMenuBtn" type="button">&larr; RETURN TO MAIN MENU</button>',
    "<script>",
    "document.getElementById('toMenuBtn').addEventListener('click', function () {",
    "  window.location.href = '/';",
    "});",
    "</script>",
    "</body>",
    "</html>"
].join("\n");

// the dashboard
export const ADMIN_PAGE = [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    HEAD,
    "<title>ZoneOut Admin</title>",
    "<style>",
    adminCss(),
    "</style>",
    "</head>",
    "<body>",
    adminBody(),
    "<script>",
    adminScript(),
    "</script>",
    "</body>",
    "</html>"
].join("\n");

// styling
function adminCss() {
    return [
        "body{background:rgb(var(--bg));color:rgb(var(--fg));line-height:1.6;min-height:100vh;padding:28px 20px 140px;}",

        ".adminTop{display:flex;flex-wrap:wrap;gap:18px;align-items:flex-start;",
        "justify-content:space-between;width:min(1180px,100%);margin:0 auto 26px;}",
        ".adminTitle{font-size:clamp(24px,4vw,34px);letter-spacing:6px;font-weight:bold;}",
        ".adminSub{margin-top:6px;font-size:14px;opacity:0.55;letter-spacing:2px;}",

        ".searchBox{margin-top:14px;width:min(420px,100%);}",
        ".searchBox label{display:block;font-size:13px;letter-spacing:3px;opacity:0.55;margin-bottom:6px;}",
        ".searchBox input{width:100%;}",
        ".searchHint{margin-top:6px;font-size:12px;opacity:0.42;line-height:1.6;}",

        ".queryBox{width:min(420px,100%);}",
        ".queryBox label{display:block;font-size:13px;letter-spacing:3px;opacity:0.55;margin-bottom:6px;}",
        ".queryBox input{width:100%;}",
        ".queryHint{margin-top:6px;font-size:12px;opacity:0.42;line-height:1.6;}",

        "input[type=text]{background:rgba(var(--panelBot),0.9);color:rgb(var(--fg));border:1px solid rgba(var(--accent),0.35);",
        "padding:9px 11px;font-size:15px;font-family:'Courier New',monospace;border-radius:4px;}",
        "input[type=text]:focus{outline:none;border-color:rgba(var(--accentBright),0.9);",
        "box-shadow:inset 0 0 0 1px rgba(var(--accentBright),0.45), inset 0 0 12px rgba(var(--accentGlow),0.18);}",

        ".adminTabs{display:flex;gap:10px;margin-bottom:10px;justify-content:flex-end;}",
        ".adminTabs .camNode{padding:7px 12px;font-size:13px;letter-spacing:2px;}",
        ".adminTabs .camNode.on{border-color:rgba(var(--accentBright),0.9);",
        "box-shadow:inset 0 0 0 1px rgba(var(--accentBright),0.5), inset 0 0 12px rgba(var(--accentGlow),0.2);}",

        ".tableWrap[hidden]{display:none;}",
        ".tableWrap{width:min(1180px,100%);margin:0 auto;overflow:auto;overscroll-behavior:contain;",
        "max-height:calc(100dvh - 300px);min-height:180px;",
        "scrollbar-color:rgba(var(--accentBright),0.85) rgba(var(--panelBot),0.9);",
        "border:1px solid rgba(var(--accent),0.35);",
        "background:linear-gradient(135deg, rgba(var(--panelTop),0.96), rgba(var(--panelBot),0.96));}",
        "body.hasPending .tableWrap{max-height:calc(100dvh - 460px);}",
        ".tableWrap::-webkit-scrollbar{width:14px;height:14px;}",
        ".tableWrap::-webkit-scrollbar-track{background:rgba(var(--panelBot),0.9);}",
        ".tableWrap::-webkit-scrollbar-thumb{background:rgba(var(--accent),0.75);",
        "border:3px solid rgba(var(--panelBot),0.9);border-radius:8px;}",
        ".tableWrap::-webkit-scrollbar-thumb:hover{background:rgba(var(--accentBright),0.95);}",
        ".tableWrap::-webkit-scrollbar-corner{background:rgba(var(--panelBot),0.9);}",
        "table{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0;font-size:14px;}",
        "th,td{padding:10px 12px;text-align:left;border-bottom:1px dashed rgba(var(--fg),0.12);",
        "white-space:nowrap;}",
        "th{font-size:12px;letter-spacing:2px;color:rgba(var(--fg),0.45);font-weight:normal;",
        "position:sticky;top:0;z-index:2;background:rgb(var(--panelTop));",
        "box-shadow:inset 0 -1px 0 rgba(var(--accent),0.45);}",
        "tr:last-child td{border-bottom:none;}",
        "td.wrap{white-space:normal;word-break:break-all;max-width:280px;}",
        "td.reason{white-space:normal;max-width:520px;line-height:1.6;}",
        ".balanceInput{width:96px;}",
        ".banned{color:rgb(var(--danger));letter-spacing:2px;}",
        ".projectIds{opacity:0.75;}",
        ".empty{padding:24px;text-align:center;opacity:0.6;}",
        "tr[hidden]{display:none;}",
        "td a{color:rgb(var(--accentLink));}",
        "mark{background:rgba(var(--accentBright),0.35);color:rgb(var(--fg));}",

        ".pending{position:fixed;left:50%;bottom:0;transform:translateX(-50%);",
        "width:min(1180px,100%);z-index:230;padding:14px 18px;",
        "background:linear-gradient(135deg, rgba(var(--panelTop),0.98), rgba(var(--panelBot),0.98));",
        "border:1px solid rgba(var(--accent),0.35);border-bottom:none;",
        "box-shadow:0 -8px 30px rgba(var(--bg),0.7);display:none;}",
        ".pending.show{display:flex;gap:16px;align-items:center;flex-wrap:wrap;}",
        ".pendingList{flex:1;min-width:220px;max-height:120px;overflow-y:auto;font-size:13px;line-height:1.8;}",
        ".pendingList div{opacity:0.85;}",

        ".reviewWrap[hidden]{display:none;}",
        ".reviewWrap{width:min(1600px,100%);margin:0 auto;display:flex;gap:16px;align-items:flex-start;}",
        ".reviewCol{flex:1;min-width:0;}",
        ".reviewCol.wide{flex:1.5;}",
        ".reviewHead{font-size:12px;letter-spacing:3px;margin-bottom:8px;display:flex;gap:8px;align-items:baseline;}",
        ".reviewHead .count{opacity:0.45;letter-spacing:1px;}",
        ".reviewCol .tableWrap{width:100%;overflow-x:hidden;}",
        ".reviewCol table{width:100%;min-width:0;font-size:13px;table-layout:fixed;}",
        ".reviewCol th,.reviewCol td{padding:8px 8px;white-space:normal;overflow-wrap:break-word;word-break:normal;}",
        ".reviewCol td.wrap{max-width:none;word-break:normal;overflow-wrap:break-word;}",
        ".reviewCol th{word-break:normal;white-space:nowrap;}",
        ".reviewCol col.colProject{width:30%;}",
        ".reviewCol col.colOwner{width:20%;}",
        ".reviewCol col.colHours{width:16%;}",
        ".reviewCol col.colLast{width:34%;}",
        ".reviewCol.wide col.colProject{width:36%;}",
        ".reviewCol.wide col.colHours{width:14%;}",
        ".reviewCol.wide col.colLast{width:30%;}",
        ".projStamp{display:block;margin-top:3px;font-size:11px;opacity:0.45;}",
        ".headReview{color:rgb(var(--reviewWait));}",
        ".headApproved{color:rgb(var(--reviewOk));}",
        ".headRejected{color:rgb(var(--reviewBad));}",
        ".rowBtn{padding:4px 9px;font-size:12px;letter-spacing:1px;}",
        ".rowBtn.ok{border-color:rgba(var(--reviewOk),0.75);color:rgb(var(--reviewOk));}",
        ".rowBtn.bad{border-color:rgba(var(--reviewBad),0.75);color:rgb(var(--reviewBad));}",
        ".rowActions{display:flex;gap:6px;flex-wrap:wrap;}",
        "tr.reviewEdit[hidden]{display:none;}",
        "tr.reviewEdit td{background:rgba(var(--accentGlow),0.1);white-space:normal;}",
        ".editLine{display:flex;gap:8px;align-items:center;flex-wrap:wrap;}",
        ".editLine input[type=text]{flex:1;min-width:160px;}",
        ".stagedMark{font-size:11px;letter-spacing:2px;color:rgb(var(--warn));}",

        ".orderWrap[hidden]{display:none;}",
        ".orderStack{flex:1;min-width:0;display:flex;flex-direction:column;gap:16px;}",
        ".orderWrap .reviewCol.wide{flex:1.4;}",
        ".orderStack .tableWrap{min-height:120px;max-height:calc(50dvh - 120px);}",
        ".orderCol col.colOrder{width:34%;}",
        ".orderCol col.colBuyer{width:26%;}",
        ".orderCol col.colSpent{width:14%;}",
        ".orderCol col.colTail{width:26%;}",
        ".orderCol.wide col.colOrder{width:30%;}",
        ".orderCol.wide col.colTail{width:30%;}",
        ".orderState{letter-spacing:2px;font-size:11px;}",
        ".orderState.statePending{color:rgb(var(--reviewWait));}",
        ".orderState.stateApproved{color:rgb(var(--reviewOk));}",
        ".orderState.stateRejected{color:rgb(var(--reviewBad));}",
        ".headOrders{color:rgba(var(--fg),0.7);}",
        ".orderRefund{letter-spacing:2px;font-size:11px;color:rgb(var(--warn));}",

        ".refundCard{width:min(520px,100%);}",
        ".refundTitle{font-size:18px;letter-spacing:4px;margin-bottom:12px;}",
        ".refundText{font-size:14px;line-height:1.7;opacity:0.85;}",
        ".refundText strong{color:rgb(var(--warn));font-weight:normal;}",
        ".refundRow{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px;}",

        ".adminMsg{width:min(1180px,100%);margin:16px auto 0;font-size:14px;line-height:1.7;min-height:20px;}",
        ".adminMsg.bad{color:rgb(var(--danger));}",

        "@media (max-width:1100px){",
        ".reviewWrap{flex-direction:column;}",
        ".orderStack{width:100%;}",
        ".reviewCol{width:100%;}",
        "}",

        "@media (max-width:700px){",
        ".tableWrap{max-height:calc(100dvh - 220px);}",
        ".adminTop{flex-direction:column;}",
        ".queryBox{width:100%;}",
        ".searchBox{width:100%;}",
        "}"
    ].join("\n");
}

// markup
function adminBody() {
    return [
        '<div class="adminTop">',
        "<div>",
        '<div class="adminTitle">ADMIN</div>',
        '<div class="adminSub" id="adminCount">loading&hellip;</div>',

        '<div class="searchBox">',
        '<label for="searchInput">SEARCH RECORDS</label>',
        '<input id="searchInput" type="text" autocomplete="off" spellcheck="false" placeholder="name, email, id, keyword">',
        '<div class="searchHint">Filters as you type. Every word must match. Escape clears.</div>',
        "</div>",
        "</div>",

        '<div class="queryBox">',
        '<div class="adminTabs">',
        '<button class="camNode on" id="tabUsers" type="button">USERS</button>',
        '<button class="camNode" id="tabProjects" type="button">PROJECTS</button>',
        '<button class="camNode" id="tabReviews" type="button">REVIEWS</button>',
        '<button class="camNode" id="tabOrders" type="button">SHOP ORDERS</button>',
        '<button class="camNode" id="tabSuggestions" type="button">SHOP SUGGESTIONS</button>',
        "</div>",
        '<label for="queryInput">QUERIES</label>',
        '<input id="queryInput" type="text" autocomplete="off" spellcheck="false" placeholder="DELETE 4 17">',
        '<div class="queryHint">',
        "DELETE &lt;user_id&gt; &lt;project_id&gt; &nbsp;&middot;&nbsp; ",
        "BAN &lt;user_id&gt; &lt;reason&gt; &nbsp;&middot;&nbsp; ",
        "UNBAN &lt;user_id&gt; &nbsp;&middot;&nbsp; ",
        "&lt;user_id&gt; ACCESS CG true|false &nbsp;&middot;&nbsp; ",
        "HACKATIME UPDATE<br>Press Enter to stage, then Save.",
        "</div>",
        "</div>",
        "</div>",

        '<div class="tableWrap" id="userWrap">',
        "<table>",
        "<thead><tr>",
        "<th>USER_ID</th><th>USERNAME</th><th>EMAIL</th><th>SLACK_ID</th><th>REGION</th>",
        "<th>HOUR_BALANCE</th><th>PROJECT_IDS</th><th>STATE</th>",
        "</tr></thead>",
        '<tbody id="adminRows"></tbody>',
        "</table>",
        '<div class="empty" id="adminEmpty">Loading&hellip;</div>',
        "</div>",

        '<div class="tableWrap" id="projectWrap" hidden>',
        "<table>",
        "<thead><tr>",
        "<th>PROJECT_ID</th><th>USER_ID</th><th>SLACK_ID</th><th>USERNAME</th><th>PROJECT_NAME</th>",
        "<th>HACKATIME_PROJECT</th><th>ACTIVE_HOURS</th><th>REGION</th><th>PROJECT_PAGE</th>",
        "<th>LINKS</th><th>CREATED</th>",
        "</tr></thead>",
        '<tbody id="projectRows"></tbody>',
        "</table>",
        '<div class="empty" id="projectEmpty">Loading&hellip;</div>',
        "</div>",

        '<div class="tableWrap" id="suggestionWrap" hidden>',
        "<table>",
        "<thead><tr>",
        "<th>ID</th><th>USER_ID</th><th>USERNAME</th><th>REGION</th>",
        "<th>SUGGESTED_ITEM</th><th>REASON</th><th>WHEN</th>",
        "</tr></thead>",
        '<tbody id="suggestionRows"></tbody>',
        "</table>",
        '<div class="empty" id="suggestionEmpty">Loading&hellip;</div>',
        "</div>",

        '<div class="reviewWrap" id="reviewWrap" hidden>',
        reviewColumn("review", "UNDER REVIEW", "headReview", true),
        reviewColumn("approved", "APPROVED", "headApproved", false),
        reviewColumn("rejected", "REJECTED", "headRejected", false),
        "</div>",

        '<div class="reviewWrap orderWrap" id="orderWrap" hidden>',
        orderColumn("order", "ALL ORDERS", "headOrders", true),
        '<div class="orderStack">',
        orderColumn("orderOk", "APPROVED ORDERS", "headApproved", false),
        orderColumn("orderBad", "REJECTED ORDERS", "headRejected", false),
        "</div>",
        "</div>",

        '<div class="modalScrim" id="refundScrim" hidden>',
        '<div class="modalCard refundCard" role="dialog" aria-modal="true" aria-labelledby="refundTitle">',
        '<button class="modalClose" id="refundClose" type="button" aria-label="Cancel">&times;</button>',
        '<div class="refundTitle" id="refundTitle">REFUND THE HOURS?</div>',
        '<div class="refundText" id="refundText"></div>',
        '<div class="refundRow">',
        '<button class="camNode rowBtn ok" id="refundYes" type="button">YES, REFUND</button>',
        '<button class="camNode rowBtn" id="refundNo" type="button">NO REFUND</button>',
        "</div>",
        "</div>",
        "</div>",

        '<div class="adminMsg" id="adminMsg" role="status" aria-live="polite"></div>',

        '<div class="pending" id="pending">',
        '<div class="pendingList" id="pendingList"></div>',
        '<button class="camNode" id="discardBtn" type="button">DISCARD</button>',
        '<button class="camNode" id="saveBtn" type="button">SAVE</button>',
        "</div>"
    ].join("\n");
}

// one of the three review tables
function reviewColumn(key, heading, tone, acting) {
    return [
        '<div class="reviewCol' + (acting ? " wide" : "") + '">',
        '<div class="reviewHead ' + tone + '">' + heading,
        '<span class="count" id="' + key + 'Count"></span>',
        "</div>",
        '<div class="tableWrap">',
        "<table>",
        '<colgroup><col class="colProject"><col class="colOwner"><col class="colHours"><col class="colLast"></colgroup>',
        "<thead><tr>",
        "<th>PROJECT</th><th>OWNER</th><th>HOURS</th>",
        acting ? "<th>ACTIONS</th>" : "<th>REMARKS</th>",
        "</tr></thead>",
        '<tbody id="' + key + 'Rows"></tbody>',
        "</table>",
        '<div class="empty" id="' + key + 'Empty">Loading&hellip;</div>',
        "</div>",
        "</div>"
    ].join("\n");
}

// one of the three order tables
function orderColumn(key, heading, tone, acting) {
    return [
        '<div class="reviewCol orderCol' + (acting ? " wide" : "") + '">',
        '<div class="reviewHead ' + tone + '">' + heading,
        '<span class="count" id="' + key + 'Count"></span>',
        "</div>",
        '<div class="tableWrap">',
        "<table>",
        '<colgroup><col class="colOrder"><col class="colBuyer"><col class="colSpent"><col class="colTail"></colgroup>',
        "<thead><tr>",
        "<th>ORDER</th><th>BUYER</th><th>HOURS</th>",
        acting ? "<th>ACTIONS</th>" : "<th>DECIDED</th>",
        "</tr></thead>",
        '<tbody id="' + key + 'Rows"></tbody>',
        "</table>",
        '<div class="empty" id="' + key + 'Empty">Loading&hellip;</div>',
        "</div>",
        "</div>"
    ].join("\n");
}

// behaviour
function adminScript() {
    return [
        '"use strict";',

        "var rowsEl = document.getElementById('adminRows');",
        "var emptyEl = document.getElementById('adminEmpty');",
        "var countEl = document.getElementById('adminCount');",
        "var msgEl = document.getElementById('adminMsg');",
        "var pendingEl = document.getElementById('pending');",
        "var pendingListEl = document.getElementById('pendingList');",
        "var queryInput = document.getElementById('queryInput');",
        "var saveBtn = document.getElementById('saveBtn');",
        "var userWrap = document.getElementById('userWrap');",
        "var suggestionWrap = document.getElementById('suggestionWrap');",
        "var suggestionRowsEl = document.getElementById('suggestionRows');",
        "var suggestionEmptyEl = document.getElementById('suggestionEmpty');",
        "var tabUsers = document.getElementById('tabUsers');",
        "var searchInput = document.getElementById('searchInput');",
        "var tabSuggestions = document.getElementById('tabSuggestions');",
        "var tabProjects = document.getElementById('tabProjects');",
        "var projectWrap = document.getElementById('projectWrap');",
        "var projectRowsEl = document.getElementById('projectRows');",
        "var projectEmptyEl = document.getElementById('projectEmpty');",

        "var tabOrders = document.getElementById('tabOrders');",
        "var orderWrap = document.getElementById('orderWrap');",
        "var ORDER_COLUMNS = {",
        "  order:   { status: null, rows: document.getElementById('orderRows'),",
        "             empty: document.getElementById('orderEmpty'), count: document.getElementById('orderCount'),",
        "             blank: 'Nobody has ordered anything yet.' },",
        "  orderOk: { status: 'approved', rows: document.getElementById('orderOkRows'),",
        "             empty: document.getElementById('orderOkEmpty'), count: document.getElementById('orderOkCount'),",
        "             blank: 'Nothing has been approved yet.' },",
        "  orderBad:{ status: 'rejected', rows: document.getElementById('orderBadRows'),",
        "             empty: document.getElementById('orderBadEmpty'), count: document.getElementById('orderBadCount'),",
        "             blank: 'Nothing has been rejected.' }",
        "};",

        "var tabReviews = document.getElementById('tabReviews');",
        "var reviewWrap = document.getElementById('reviewWrap');",
        "var REVIEW_COLUMNS = {",
        "  review:   { status: 'under_review', rows: document.getElementById('reviewRows'),",
        "              empty: document.getElementById('reviewEmpty'), count: document.getElementById('reviewCount'),",
        "              blank: 'Nothing is waiting for a decision.' },",
        "  approved: { status: 'approved', rows: document.getElementById('approvedRows'),",
        "              empty: document.getElementById('approvedEmpty'), count: document.getElementById('approvedCount'),",
        "              blank: 'Nothing has been approved yet.' },",
        "  rejected: { status: 'rejected', rows: document.getElementById('rejectedRows'),",
        "              empty: document.getElementById('rejectedEmpty'), count: document.getElementById('rejectedCount'),",
        "              blank: 'Nothing has been rejected.' }",
        "};",

        "// staged edits, nothing written until Save",
        "var stagedBalances = new Map();",
        "var stagedCommands = [];",
        "var stagedReviews = new Map();",
        "var stagedOrders = new Map();",
        "var users = [];",
        "var reviews = [];",
        "var orders = [];",

        "// live search index, one entry per drawn row",
        "var userIndex = [];",
        "var suggestionIndex = [];",
        "var suggestionsDrawn = false;",
        "var projectIndex = [];",
        "var projectsDrawn = false;",
        "var reviewIndex = [];",
        "var reviewsDrawn = false;",
        "var orderIndex = [];",
        "var ordersDrawn = false;",

        "function say(text, bad) {",
        "  msgEl.textContent = text || '';",
        "  msgEl.classList.toggle('bad', Boolean(bad));",
        "}",

        "// a 404 means this session is no longer an administrator",
        "function handleGone(response) {",
        "  if (response.status === 404) { location.reload(); return true; }",
        "  return false;",
        "}",

        "function load() {",
        "  fetch('/api/admin/users', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the user list.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) render(data.users); })",
        "    .catch(function (err) {",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      emptyEl.textContent = 'Could not load.';",
        "    });",
        "}",

        "function render(list) {",
        "  users = list || [];",
        "  rowsEl.textContent = '';",
        "  userIndex = [];",

        "  users.forEach(function (user) {",
        "    var tr = document.createElement('tr');",
        "    tr.appendChild(cell(String(user.userId)));",
        "    tr.appendChild(cell(user.name || '\\u2014'));",
        "    tr.appendChild(cell(user.email, 'wrap'));",
        "    tr.appendChild(cell(user.slackId || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(user.region || '\\u2014'));",

        "    // balance field",
        "    var td = document.createElement('td');",
        "    var input = document.createElement('input');",
        "    input.type = 'text';",
        "    input.className = 'balanceInput';",
        "    input.value = String(user.balanceHours);",
        "    input.setAttribute('aria-label', 'Hour balance for user ' + user.userId);",
        "    input.addEventListener('input', function () {",
        "      var raw = input.value.trim();",
        "      var value = Number(raw);",
        "      if (raw === '' || !isFinite(value) || value < 0 || value === user.balanceHours) {",
        "        stagedBalances['delete'](user.userId);",
        "      } else {",
        "        stagedBalances.set(user.userId, value);",
        "      }",
        "      renderPending();",
        "    });",
        "    td.appendChild(input);",
        "    tr.appendChild(td);",

        "    var ids = Array.isArray(user.projectIds) ? user.projectIds : [];",
        "    tr.appendChild(cell(ids.length ? ids.join(', ') : '\\u2014', 'projectIds'));",

        "    var state = document.createElement('td');",
        "    if (user.isBanned) {",
        "      state.className = 'banned';",
        "      state.textContent = 'BANNED';",
        "      state.title = user.banReason || '';",
        "    } else {",
        "      state.textContent = user.status + (user.hackatimeLinked ? ' + hackatime' : '')",
        "                          + (user.cgAccess ? ' + cg' : '');",
        "    }",
        "    state.dataset.text = state.textContent;",
        "    tr.appendChild(state);",
        "    rowsEl.appendChild(tr);",
        "    indexRow(userIndex, tr, String(user.balanceHours) + ' ' + (user.banReason || ''));",
        "  });",

        "  applyFilter();",
        "  renderPending();",
        "}",

        "// table cells",
        "function cell(text, className) {",
        "  var td = document.createElement('td');",
        "  if (className) td.className = className;",
        "  td.textContent = text;",
        "  td.dataset.text = text;",
        "  return td;",
        "}",

        "function renderPending() {",
        "  var lines = [];",
        "  stagedBalances.forEach(function (hours, userId) {",
        "    lines.push('set user ' + userId + ' balance to ' + hours);",
        "  });",
        "  stagedCommands.forEach(function (raw) { lines.push(raw); });",
        "  stagedReviews.forEach(function (entry, projectId) {",
        "    lines.push(entry.decision + ' project ' + projectId + ' — “' + entry.remarks + '”');",
        "  });",
        "  stagedOrders.forEach(function (entry, orderId) {",
        "    lines.push(entry.decision + ' order ' + orderId",
        "               + (entry.refund ? ' and refund ' + entry.hours + ' hours' : ''));",
        "  });",

        "  pendingListEl.textContent = '';",
        "  lines.forEach(function (line) {",
        "    var div = document.createElement('div');",
        "    div.textContent = '\\u203a ' + line;",
        "    pendingListEl.appendChild(div);",
        "  });",

        "  pendingEl.classList.toggle('show', lines.length > 0);",
        "  document.body.classList.toggle('hasPending', lines.length > 0);",
        "}",

        "// command box",
        "queryInput.addEventListener('keydown', function (e) {",
        "  if (e.key !== 'Enter') return;",
        "  e.preventDefault();",
        "  var raw = queryInput.value.trim();",
        "  if (!raw) return;",
        "  stagedCommands.push(raw);",
        "  queryInput.value = '';",
        "  say('');",
        "  renderPending();",
        "});",

        "document.getElementById('discardBtn').addEventListener('click', function () {",
        "  stagedBalances.clear();",
        "  stagedCommands = [];",
        "  stagedReviews.clear();",
        "  stagedOrders.clear();",
        "  say('Discarded.');",
        "  render(users);",
        "  if (reviewsDrawn) renderReviews(reviews);",
        "  if (ordersDrawn) renderOrders(orders);",
        "});",

        "saveBtn.addEventListener('click', function () {",
        "  var balances = [];",
        "  stagedBalances.forEach(function (hours, userId) {",
        "    balances.push({ userId: userId, balanceHours: hours });",
        "  });",
        "  var staged = [];",
        "  stagedReviews.forEach(function (entry, projectId) {",
        "    staged.push({ projectId: projectId, decision: entry.decision, remarks: entry.remarks });",
        "  });",
        "  var decided = [];",
        "  stagedOrders.forEach(function (entry, orderId) {",
        "    decided.push({ orderId: orderId, decision: entry.decision, refund: entry.refund });",
        "  });",
        "  if (!balances.length && !stagedCommands.length && !staged.length && !decided.length) return;",

        "  saveBtn.disabled = true;",
        "  say('Saving\\u2026');",

        "  fetch('/api/admin/apply', {",
        "    method: 'POST',",
        "    credentials: 'same-origin',",
        "    headers: { 'Content-Type': 'application/json' },",
        "    body: JSON.stringify({ balances: balances, commands: stagedCommands,",
        "                            reviews: staged, orders: decided })",
        "  })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      return r.json().then(function (data) { return { ok: r.ok, data: data }; });",
        "    })",
        "    .then(function (result) {",
        "      if (!result) return;",
        "      if (!result.ok) {",
        "        // the batch rolled back; staged changes stay put",
        "        say(result.data.error || 'Could not save.', true);",
        "        return;",
        "      }",
        "      stagedBalances.clear();",
        "      stagedCommands = [];",
        "      stagedReviews.clear();",
        "      stagedOrders.clear();",
        "      if (result.data.users) { render(result.data.users); } else { load(); }",
        "      if (result.data.reviews) { renderReviews(result.data.reviews); }",
        "      else if (reviewsDrawn) { reviewsLoaded = false; loadReviews(); }",
        "      if (result.data.orders) { renderOrders(result.data.orders); }",
        "      else if (ordersDrawn) { ordersLoaded = false; loadOrders(); }",
        "      say('Saved: ' + (result.data.applied || []).join('; '));",
        "    })",
        "    .catch(function () { say('Could not reach ZoneOut.', true); })",
        "    .then(function () { saveBtn.disabled = false; });",
        "});",

        "// reviews",
        "var reviewsLoaded = false;",

        "function loadReviews() {",
        "  if (reviewsLoaded) return;",
        "  reviewsLoaded = true;",

        "  fetch('/api/admin/reviews', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the review list.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) renderReviews(data.reviews); })",
        "    .catch(function (err) {",
        "      reviewsLoaded = false;",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      eachColumn(function (col) { col.empty.textContent = 'Could not load.'; });",
        "    });",
        "}",

        "function eachColumn(fn) {",
        "  Object.keys(REVIEW_COLUMNS).forEach(function (key) { fn(REVIEW_COLUMNS[key], key); });",
        "}",

        "function renderReviews(list) {",
        "  reviews = list || [];",
        "  reviewIndex = [];",
        "  reviewsDrawn = true;",

        "  eachColumn(function (col) { col.rows.textContent = ''; col.drawn = 0; });",

        "  reviews.forEach(function (row) {",
        "    var col = columnFor(row.reviewStatus);",
        "    if (!col) return;",

        "    var acting = row.reviewStatus === 'under_review';",
        "    var tr = document.createElement('tr');",

        "    tr.appendChild(projectCell(row, acting));",
        "    tr.appendChild(cell(row.ownerName || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(String(Number(row.hackatimeHours) || 0)));",
        "    tr.appendChild(acting ? actionCell(row, tr) : cell(row.reviewRemarks || '\u2014', 'wrap'));",

        "    col.rows.appendChild(tr);",
        "    col.drawn++;",
        "    indexRow(reviewIndex, tr, (row.name || '') + ' ' + (row.email || '')",
        "                              + ' ' + (row.slackId || '') + ' ' + row.reviewStatus",
        "                              + ' /projects/' + row.projectId);",
        "  });",

        "  applyFilter();",
        "}",

        "function projectCell(row, acting) {",
        "  var td = projectPage(row.projectId, '#' + row.projectId + ' ' + (row.name || 'untitled'));",
        "  var stamp = document.createElement('span');",
        "  stamp.className = 'projStamp';",
        "  stamp.textContent = when(acting ? row.submittedAt : row.reviewedAt);",
        "  td.appendChild(stamp);",
        "  return td;",
        "}",

        "function columnFor(status) {",
        "  var found = null;",
        "  eachColumn(function (col) { if (col.status === status) found = col; });",
        "  return found;",
        "}",

        "// the decision is staged, never written here",
        "function actionCell(row, tr) {",
        "  var td = document.createElement('td');",
        "  var wrap = document.createElement('div');",
        "  wrap.className = 'rowActions';",

        "  var staged = stagedReviews.get(row.projectId);",
        "  if (staged) {",
        "    var mark = document.createElement('span');",
        "    mark.className = 'stagedMark';",
        "    mark.textContent = 'STAGED ' + staged.decision.toUpperCase();",
        "    wrap.appendChild(mark);",
        "  }",

        "  wrap.appendChild(decisionButton(row, tr, 'approve', 'APPROVE', 'ok'));",
        "  wrap.appendChild(decisionButton(row, tr, 'reject', 'REJECT', 'bad'));",

        "  td.appendChild(wrap);",
        "  return td;",
        "}",

        "function decisionButton(row, tr, decision, label, tone) {",
        "  var button = document.createElement('button');",
        "  button.type = 'button';",
        "  button.className = 'camNode rowBtn ' + tone;",
        "  button.textContent = label;",
        "  button.addEventListener('click', function () { openRowEditor(row, tr, decision); });",
        "  return button;",
        "}",

        "function openRowEditor(row, tr, decision) {",
        "  closeRowEditor(tr);",

        "  var edit = document.createElement('tr');",
        "  edit.className = 'reviewEdit';",

        "  var td = document.createElement('td');",
        "  td.colSpan = 4;",

        "  var line = document.createElement('div');",
        "  line.className = 'editLine';",

        "  var label = document.createElement('span');",
        "  label.textContent = decision === 'approve' ? 'APPROVE \u2014 REMARKS' : 'REJECT \u2014 REMARKS';",
        "  label.className = decision === 'approve' ? 'headApproved' : 'headRejected';",

        "  var input = document.createElement('input');",
        "  input.type = 'text';",
        "  input.maxLength = 500;",
        "  input.setAttribute('aria-label', 'Remarks for project ' + row.projectId);",
        "  var held = stagedReviews.get(row.projectId);",
        "  input.value = held && held.decision === decision ? held.remarks : '';",

        "  var confirm = document.createElement('button');",
        "  confirm.type = 'button';",
        "  confirm.className = 'camNode rowBtn ' + (decision === 'approve' ? 'ok' : 'bad');",
        "  confirm.textContent = 'CONFIRM';",

        "  var cancel = document.createElement('button');",
        "  cancel.type = 'button';",
        "  cancel.className = 'camNode rowBtn';",
        "  cancel.textContent = 'CANCEL';",

        "  var stage = function () {",
        "    var remarks = input.value.trim();",
        "    if (!remarks) { say('Remarks are required.', true); input.focus(); return; }",
        "    stagedReviews.set(row.projectId, { decision: decision, remarks: remarks });",
        "    say('');",
        "    renderPending();",
        "    renderReviews(reviews);",
        "  };",

        "  confirm.addEventListener('click', stage);",
        "  input.addEventListener('keydown', function (e) {",
        "    if (e.key === 'Enter') { e.preventDefault(); stage(); }",
        "    if (e.key === 'Escape') { e.preventDefault(); closeRowEditor(tr); }",
        "  });",
        "  cancel.addEventListener('click', function () { closeRowEditor(tr); });",

        "  line.appendChild(label);",
        "  line.appendChild(input);",
        "  line.appendChild(confirm);",
        "  line.appendChild(cancel);",
        "  td.appendChild(line);",
        "  edit.appendChild(td);",

        "  tr.parentNode.insertBefore(edit, tr.nextSibling);",
        "  tr.reviewEditor = edit;",
        "  input.focus();",
        "}",

        "function closeRowEditor(tr) {",
        "  if (tr.reviewEditor && tr.reviewEditor.parentNode) tr.reviewEditor.parentNode.removeChild(tr.reviewEditor);",
        "  tr.reviewEditor = null;",
        "}",

        "// section for shop orders",
        "var ordersLoaded = false;",

        "function loadOrders() {",
        "  if (ordersLoaded) return;",
        "  ordersLoaded = true;",

        "  fetch('/api/admin/orders', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the order list.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) renderOrders(data.orders); })",
        "    .catch(function (err) {",
        "      ordersLoaded = false;",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      eachOrderColumn(function (col) { col.empty.textContent = 'Could not load.'; });",
        "    });",
        "}",

        "function eachOrderColumn(fn) {",
        "  Object.keys(ORDER_COLUMNS).forEach(function (key) { fn(ORDER_COLUMNS[key], key); });",
        "}",

        "function renderOrders(list) {",
        "  orders = list || [];",
        "  orderIndex = [];",
        "  ordersDrawn = true;",

        "  eachOrderColumn(function (col) { col.rows.textContent = ''; col.drawn = 0; });",

        "  orders.forEach(function (row) {",
        "    drawOrder(ORDER_COLUMNS.order, row, true);",
        "    if (row.status === 'approved') drawOrder(ORDER_COLUMNS.orderOk, row, false);",
        "    if (row.status === 'rejected') drawOrder(ORDER_COLUMNS.orderBad, row, false);",
        "  });",

        "  applyFilter();",
        "}",

        "function drawOrder(col, row, acting) {",
        "  var tr = document.createElement('tr');",
        "  tr.appendChild(orderCell(row));",
        "  tr.appendChild(cell((row.userName || '\u2014') + ' #' + row.userId, 'wrap'));",
        "  tr.appendChild(cell(String(Number(row.hoursSpent) || 0)));",
        "  tr.appendChild(acting ? orderActionCell(row)",
        "                        : cell(when(row.reviewedAt) + (row.refunded ? ' · refunded' : ''), 'wrap'));",
        "  col.rows.appendChild(tr);",
        "  col.drawn++;",
        "  indexRow(orderIndex, tr, '#' + row.orderId + ' ' + (row.itemName || '')",
        "                           + ' ' + (row.itemId || '') + ' ' + (row.email || '')",
        "                           + ' ' + (row.slackId || '') + ' ' + (row.region || '')",
        "                           + ' ' + row.status + (row.refunded ? ' refunded' : ''));",
        "}",

        "// the item, quantity and when it was placed",
        "function orderCell(row) {",
        "  var td = document.createElement('td');",
        "  td.className = 'wrap';",
        "  var head = document.createElement('div');",
        "  head.textContent = '#' + row.orderId + ' ' + (row.itemName || 'unknown')",
        "                     + ' \u00d7' + row.quantity;",
        "  td.appendChild(head);",
        "  var stamp = document.createElement('span');",
        "  stamp.className = 'projStamp';",
        "  stamp.textContent = when(row.createdAt) + ' \u00b7 ' + (row.region || 'global');",
        "  td.appendChild(stamp);",
        "  return td;",
        "}",

        "// the decision is staged, never written here",
        "function orderActionCell(row) {",
        "  var td = document.createElement('td');",
        "  var wrap = document.createElement('div');",
        "  wrap.className = 'rowActions';",

        "  var state = document.createElement('span');",
        "  state.className = 'orderState state' + row.status.charAt(0).toUpperCase() + row.status.slice(1);",
        "  state.textContent = row.status.toUpperCase();",
        "  wrap.appendChild(state);",

        "  if (row.refunded) {",
        "    var paid = document.createElement('span');",
        "    paid.className = 'orderRefund';",
        "    paid.textContent = 'REFUNDED';",
        "    wrap.appendChild(paid);",
        "  }",

        "  var held = stagedOrders.get(row.orderId);",
        "  if (held) {",
        "    var mark = document.createElement('span');",
        "    mark.className = 'stagedMark';",
        "    mark.textContent = 'STAGED ' + held.decision.toUpperCase()",
        "                       + (held.refund ? ' + REFUND' : '');",
        "    wrap.appendChild(mark);",
        "  }",

        "  wrap.appendChild(orderButton(row, 'approve', 'APPROVE', 'ok'));",
        "  wrap.appendChild(orderButton(row, 'reject', 'REJECT', 'bad'));",

        "  td.appendChild(wrap);",
        "  return td;",
        "}",

        "function orderButton(row, decision, label, tone) {",
        "  var button = document.createElement('button');",
        "  button.type = 'button';",
        "  button.className = 'camNode rowBtn ' + tone;",
        "  button.textContent = label;",
        "  button.addEventListener('click', function () {",
        "    var held = stagedOrders.get(row.orderId);",
        "    if (held && held.decision === decision) { stageOrder(row, null, false); return; }",
        "    if (decision === 'reject' && !row.refunded) { askRefund(row, button); return; }",
        "    stageOrder(row, decision, false);",
        "  });",
        "  return button;",
        "}",

        "function stageOrder(row, decision, refund) {",
        "  if (!decision) stagedOrders['delete'](row.orderId);",
        "  else stagedOrders.set(row.orderId, { decision: decision, refund: Boolean(refund),",
        "                                       hours: Number(row.hoursSpent) || 0 });",
        "  say('');",
        "  renderPending();",
        "  renderOrders(orders);",
        "}",

        "// a rejection is asked about the hours before it is staged",
        "var refundScrim = document.getElementById('refundScrim');",
        "var refundTextEl = document.getElementById('refundText');",
        "var refundRow = null;",
        "var refundFocus = null;",

        "function askRefund(row, opener) {",
        "  refundRow = row;",
        "  refundFocus = opener;",
        "  refundTextEl.textContent = '';",
        "  refundTextEl.appendChild(document.createTextNode('Rejecting order #' + row.orderId + ' — '",
        "    + (row.itemName || 'unknown') + ' ×' + row.quantity + ' for '",
        "    + (row.userName || 'unknown') + ' #' + row.userId + '. Give back the '));",
        "  var hours = document.createElement('strong');",
        "  hours.textContent = (Number(row.hoursSpent) || 0) + ' hours';",
        "  refundTextEl.appendChild(hours);",
        "  refundTextEl.appendChild(document.createTextNode(' they spent?'));",

        "  refundScrim.hidden = false;",
        "  requestAnimationFrame(function () { refundScrim.classList.add('show'); });",
        "  setTimeout(function () { refundScrim.classList.add('show'); }, 60);",
        "  setInertBehind(true);",
        "  document.getElementById('refundNo').focus();",
        "}",

        "function closeRefund() {",
        "  refundScrim.classList.remove('show');",
        "  setInertBehind(false);",
        "  setTimeout(function () { refundScrim.hidden = true; }, 200);",
        "  refundRow = null;",
        "  if (refundFocus && refundFocus.isConnected) refundFocus.focus();",
        "  refundFocus = null;",
        "}",

        "function setInertBehind(on) {",
        "  var kids = document.body.children;",
        "  for (var i = 0; i < kids.length; i++) {",
        "    if (kids[i] === refundScrim) continue;",
        "    if (on) { kids[i].dataset.wasInert = kids[i].inert ? '1' : '0'; kids[i].inert = true; }",
        "    else { kids[i].inert = kids[i].dataset.wasInert === '1'; }",
        "  }",
        "}",

        "function decideRefund(refund) {",
        "  var row = refundRow;",
        "  closeRefund();",
        "  if (row) stageOrder(row, 'reject', refund);",
        "}",

        "document.getElementById('refundYes').addEventListener('click', function () { decideRefund(true); });",
        "document.getElementById('refundNo').addEventListener('click', function () { decideRefund(false); });",
        "document.getElementById('refundClose').addEventListener('click', closeRefund);",
        "refundScrim.addEventListener('mousedown', function (e) { if (e.target === refundScrim) closeRefund(); });",

        "document.addEventListener('keydown', function (e) {",
        "  if (refundScrim.hidden) return;",
        "  if (e.key === 'Escape') { e.preventDefault(); closeRefund(); }",
        "});",

        "// live search",
        "function indexRow(index, tr, extra) {",
        "  var cells = [];",
        "  var tds = tr.querySelectorAll('td');",
        "  for (var i = 0; i < tds.length; i++) {",
        "    if (typeof tds[i].dataset.text === 'string') cells.push({ td: tds[i], text: tds[i].dataset.text });",
        "  }",
        "  var text = cells.map(function (c) { return c.text; }).join(' ') + ' ' + (extra || '');",
        "  index.push({ tr: tr, cells: cells, text: text.toLowerCase() });",
        "}",

        "function searchTerms() {",
        "  var raw = searchInput.value.trim().toLowerCase();",
        "  return raw ? raw.split(/\\s+/) : [];",
        "}",

        "function termPattern(terms) {",
        "  if (!terms.length) return null;",
        "  var escaped = terms.map(function (t) { return t.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&'); });",
        "  return new RegExp('(' + escaped.join('|') + ')', 'gi');",
        "}",

        "function paintCell(td, text, pattern) {",
        "  if (!pattern) { td.textContent = text; return; }",
        "  td.textContent = '';",
        "  var last = 0;",
        "  var match;",
        "  pattern.lastIndex = 0;",
        "  while ((match = pattern.exec(text)) !== null) {",
        "    if (!match[0]) { pattern.lastIndex++; continue; }",
        "    if (match.index > last) td.appendChild(document.createTextNode(text.slice(last, match.index)));",
        "    var hit = document.createElement('mark');",
        "    hit.textContent = match[0];",
        "    td.appendChild(hit);",
        "    last = match.index + match[0].length;",
        "  }",
        "  if (last < text.length) td.appendChild(document.createTextNode(text.slice(last)));",
        "}",

        "function filterIndex(index, terms, pattern) {",
        "  var shown = 0;",
        "  index.forEach(function (row) {",
        "    var hit = terms.every(function (term) { return row.text.indexOf(term) !== -1; });",
        "    row.tr.hidden = !hit;",
        "    if (!hit) return;",
        "    shown++;",
        "    row.cells.forEach(function (c) { paintCell(c.td, c.text, pattern); });",
        "  });",
        "  return shown;",
        "}",

        "function applyFilter() {",
        "  var terms = searchTerms();",
        "  var pattern = termPattern(terms);",
        "  var shownUsers = filterIndex(userIndex, terms, pattern);",
        "  var shownSuggestions = filterIndex(suggestionIndex, terms, pattern);",
        "  var shownProjects = filterIndex(projectIndex, terms, pattern);",
        "  filterIndex(reviewIndex, terms, pattern);",
        "  filterIndex(orderIndex, terms, pattern);",

        "  countEl.textContent = terms.length",
        "    ? shownUsers + ' of ' + userIndex.length + ' users matched'",
        "    : userIndex.length + ' registered';",

        "  emptyEl.style.display = shownUsers ? 'none' : '';",
        "  emptyEl.textContent = userIndex.length ? 'No records match.' : 'No one has registered yet.';",

        "  if (projectsDrawn) {",
        "    projectEmptyEl.style.display = shownProjects ? 'none' : '';",
        "    projectEmptyEl.textContent = projectIndex.length ? 'No records match.' : 'No projects have been created yet.';",
        "  }",

        "  if (suggestionsDrawn) {",
        "    suggestionEmptyEl.style.display = shownSuggestions ? 'none' : '';",
        "    suggestionEmptyEl.textContent = suggestionIndex.length ? 'No records match.' : 'Nobody has suggested anything yet.';",
        "  }",

        "  if (ordersDrawn) eachOrderColumn(function (col) {",
        "    var shown = 0;",
        "    var kids = col.rows.children;",
        "    for (var i = 0; i < kids.length; i++) { if (!kids[i].hidden) shown++; }",
        "    col.count.textContent = terms.length ? shown + ' of ' + col.drawn : String(col.drawn);",
        "    col.empty.style.display = shown ? 'none' : '';",
        "    col.empty.textContent = col.drawn ? 'No records match.' : col.blank;",
        "  });",

        "  if (reviewsDrawn) eachColumn(function (col) {",
        "    var shown = 0;",
        "    var kids = col.rows.children;",
        "    for (var i = 0; i < kids.length; i++) {",
        "      if (!kids[i].hidden && kids[i].className !== 'reviewEdit') shown++;",
        "    }",
        "    col.count.textContent = terms.length ? shown + ' of ' + col.drawn : String(col.drawn);",
        "    col.empty.style.display = shown ? 'none' : '';",
        "    col.empty.textContent = col.drawn ? 'No records match.' : col.blank;",
        "  });",
        "}",

        "searchInput.addEventListener('input', applyFilter);",

        "searchInput.addEventListener('keydown', function (e) {",
        "  if (e.key !== 'Escape') return;",
        "  searchInput.value = '';",
        "  applyFilter();",
        "});",

        "// tabs",
        "var suggestionsLoaded = false;",

        "function showTab(name) {",
        "  userWrap.hidden = name !== 'users';",
        "  projectWrap.hidden = name !== 'projects';",
        "  suggestionWrap.hidden = name !== 'suggestions';",
        "  reviewWrap.hidden = name !== 'reviews';",
        "  orderWrap.hidden = name !== 'orders';",
        "  tabUsers.classList.toggle('on', name === 'users');",
        "  tabProjects.classList.toggle('on', name === 'projects');",
        "  tabSuggestions.classList.toggle('on', name === 'suggestions');",
        "  tabReviews.classList.toggle('on', name === 'reviews');",
        "  tabOrders.classList.toggle('on', name === 'orders');",
        "  if (name === 'projects') loadProjects();",
        "  if (name === 'suggestions') loadSuggestions();",
        "  if (name === 'reviews') loadReviews();",
        "  if (name === 'orders') loadOrders();",
        "}",

        "var projectsLoaded = false;",

        "function loadProjects() {",
        "  if (projectsLoaded) return;",
        "  projectsLoaded = true;",

        "  fetch('/api/admin/projects', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the project list.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) renderProjects(data.projects); })",
        "    .catch(function (err) {",
        "      projectsLoaded = false;",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      projectEmptyEl.textContent = 'Could not load.';",
        "    });",
        "}",

        "function renderProjects(list) {",
        "  var rows = list || [];",
        "  projectRowsEl.textContent = '';",
        "  projectIndex = [];",
        "  projectsDrawn = true;",

        "  rows.forEach(function (row) {",
        "    var tr = document.createElement('tr');",
        "    tr.appendChild(cell(String(row.projectId)));",
        "    tr.appendChild(cell(String(row.userId)));",
        "    tr.appendChild(cell(row.slackId || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(row.ownerName || '\u2014'));",
        "    tr.appendChild(cell(row.name || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(row.hackatimeProject || '\u2014', 'wrap'));",
        "    tr.appendChild(cell(String(Number(row.hackatimeHours) || 0)));",
        "    tr.appendChild(cell(row.region || '\u2014'));",
        "    tr.appendChild(projectPage(row.projectId));",
        "    tr.appendChild(links(row));",
        "    tr.appendChild(cell(when(row.createdAt)));",
        "    projectRowsEl.appendChild(tr);",
        "    indexRow(projectIndex, tr, (row.email || '') + ' ' + (row.description || '')",
        "                                + ' /projects/' + row.projectId);",
        "  });",

        "  applyFilter();",
        "}",

        "// the project's own page on zoneout",
        "function projectPage(projectId, label) {",
        "  var td = document.createElement('td');",
        "  var path = '/projects/' + projectId;",
        "  var text = label || path;",
        "  var a = document.createElement('a');",
        "  a.href = path;",
        "  a.target = '_blank';",
        "  a.rel = 'noopener noreferrer';",
        "  a.textContent = text;",
        "  td.appendChild(a);",
        "  if (label) td.className = 'wrap';",
        "  return td;",
        "}",

        "// only http and https are ever rendered as a link",
        "function safeUrl(value) {",
        "  if (typeof value !== 'string' || !value) return false;",
        "  try {",
        "    var protocol = new URL(value, location.href).protocol;",
        "    return protocol === 'http:' || protocol === 'https:';",
        "  } catch (err) { return false; }",
        "}",

        "// repository and demo links",
        "function links(row) {",
        "  var td = document.createElement('td');",
        "  var pairs = [['repo', row.repoUrl], ['demo', row.demoUrl]];",
        "  var drawn = 0;",
        "  pairs.forEach(function (pair) {",
        "    if (!safeUrl(pair[1])) return;",
        "    if (drawn) td.appendChild(document.createTextNode(' \u00b7 '));",
        "    var a = document.createElement('a');",
        "    a.href = pair[1];",
        "    a.target = '_blank';",
        "    a.rel = 'noopener noreferrer nofollow';",
        "    a.textContent = pair[0];",
        "    td.appendChild(a);",
        "    drawn++;",
        "  });",
        "  if (!drawn) { td.textContent = '\u2014'; td.dataset.text = '\u2014'; }",
        "  return td;",
        "}",

        "function loadSuggestions() {",
        "  if (suggestionsLoaded) return;",
        "  suggestionsLoaded = true;",

        "  fetch('/api/admin/suggestions', { credentials: 'same-origin' })",
        "    .then(function (r) {",
        "      if (handleGone(r)) return null;",
        "      if (!r.ok) throw new Error('Could not load the suggestions.');",
        "      return r.json();",
        "    })",
        "    .then(function (data) { if (data) renderSuggestions(data.suggestions); })",
        "    .catch(function (err) {",
        "      suggestionsLoaded = false;",
        "      say(err.message || 'Could not reach ZoneOut.', true);",
        "      suggestionEmptyEl.textContent = 'Could not load.';",
        "    });",
        "}",

        "function renderSuggestions(list) {",
        "  var rows = list || [];",
        "  suggestionRowsEl.textContent = '';",
        "  suggestionIndex = [];",
        "  suggestionsDrawn = true;",

        "  rows.forEach(function (row) {",
        "    var tr = document.createElement('tr');",
        "    tr.appendChild(cell(String(row.suggestionId)));",
        "    tr.appendChild(cell(String(row.userId)));",
        "    tr.appendChild(cell(row.userName || '\u2014'));",
        "    tr.appendChild(cell(row.region || '\u2014'));",
        "    tr.appendChild(cell(row.itemName, 'wrap'));",
        "    tr.appendChild(cell(row.reason, 'reason'));",
        "    tr.appendChild(cell(when(row.createdAt)));",
        "    suggestionRowsEl.appendChild(tr);",
        "    indexRow(suggestionIndex, tr, '');",
        "  });",

        "  applyFilter();",
        "}",

        "function when(value) {",
        "  var date = new Date(value);",
        "  return isNaN(date.getTime()) ? '\u2014' : date.toLocaleString();",
        "}",

        "tabUsers.addEventListener('click', function () { showTab('users'); });",
        "tabProjects.addEventListener('click', function () { showTab('projects'); });",
        "tabSuggestions.addEventListener('click', function () { showTab('suggestions'); });",
        "tabReviews.addEventListener('click', function () { showTab('reviews'); });",
        "tabOrders.addEventListener('click', function () { showTab('orders'); });",

        "load();"
    ].join("\n");
}
