-- project review state

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS review_status        text NOT NULL DEFAULT 'draft',
    ADD COLUMN IF NOT EXISTS review_remarks       text,
    ADD COLUMN IF NOT EXISTS reviewed_at          timestamptz,
    ADD COLUMN IF NOT EXISTS reviewed_by          integer REFERENCES users(user_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS submitted_at         timestamptz,
    ADD COLUMN IF NOT EXISTS submitted_hours      numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS review_submission_id text;

DO $$
BEGIN
    ALTER TABLE projects
        ADD CONSTRAINT projects_review_status_check
        CHECK (review_status IN ('draft', 'under_review', 'approved', 'rejected'));
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE projects
        ADD CONSTRAINT projects_submitted_hours_check CHECK (submitted_hours >= 0);
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- the admin reviews panel reads by state
CREATE INDEX IF NOT EXISTS projects_review_status_idx
    ON projects(review_status, submitted_at DESC);

-- every state change, append only

CREATE TABLE IF NOT EXISTS project_reviews (
    review_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    status     text NOT NULL,
    remarks    text,
    actor_id   integer REFERENCES users(user_id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
    ALTER TABLE project_reviews
        ADD CONSTRAINT project_reviews_status_check
        CHECK (status IN ('under_review', 'approved', 'rejected'));
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS project_reviews_project_idx
    ON project_reviews(project_id, created_at DESC);
